### Using Matplotlib & Numpy to make animation

楊峻嘉

### 大綱

- 認識動畫的原理
- Numpy的基礎函式
- 製作Matplotlib動畫的基本操作
- 實際演練

### 動畫的原理

透過許多圖片快速播放，造成視覺暫留，讓我們覺得圖片中的東西好像在移動


### 製作動畫需要甚麼呢?  

圖片

### 很多的圖片! ! !

### 哪我要怎麼做出很多圖片呢?

### 用你方才學的Matplotlib加上一點小技巧 

### 但要學小技巧之前，你得要再學一個工具才行

### Numpy  

提供許多科學計算的函式

### 接下來你會學到這幾個函式

- numpy.array()
- numpy.linspace()
- numpy.arange()

### numpy.array() :建立ndarray (Numpy中的陣列)

In [1]:
import numpy as np 

a=np.array([1,2,3])
print(a)
print(type(a))

n=np.array(range(10))
print(n)
print(type(n))

[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


### numpy.linspace()  :用來建立一定範圍內的等分點





In [2]:
import numpy as np

n=np.linspace(1,19,10)
print(n)
print(type(n))

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

print(np.linspace(-1,-10,10))

[ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]


### numpy.arange() :類似range()的功能，但傳回來的物件不同

In [4]:
for i in range(0,10,2):
    print(i)
a=range(0,10,2)
print(a)
print(type(a))

0
2
4
6
8
range(0, 10, 2)
<class 'range'>


In [5]:
import numpy as np 

for i in np.arange(0,10,2):
    print(i)
a=np.arange(0,10,2)
print(a)
print(type(a))

0
2
4
6
8
[0 2 4 6 8]
<class 'numpy.ndarray'>


#### Practice
請生成15個點並描點畫出: y=f(x)=2^(-x)+2  
x的範圍請限制在-3到3之間

In [6]:
import matplotlib.pyplot as plt
import numpy as np
'''
To do: Set x and y
To do: Plot(scatter)
'''
plt.title('y=2^(-x)+2')
plt.ylabel('y',rotation=0)
plt.xlabel('x')
plt.grid()
plt.show()

<Figure size 640x480 with 1 Axes>

### 參考解答:
![numpy_example.png](https://raw.githubusercontent.com/ChunChiaYang/Python-course/master/images/numpy_example.png)
<a href='http://nbviewer.jupyter.org/github/ChunChiaYang/Python-course/blob/master/numpy_example.ipynb'><font color="white" size='15'>☣<font></a>

### Matplotlib 動畫

### 用Matplotlib你可以畫出像這樣的動畫

[![video](https://img.youtube.com/vi/CIfI-CKNp6o/hqdefault.jpg)](https://www.youtube.com/watch?v=CIfI-CKNp6o)